// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/geolocation/service/geolocationData.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	domain "github.com/aruna-cande/geolocation/pkg/geolocation/domain"
)

// MockGeolocationDataService is a mock of GeolocationDataService interface.
type MockGeolocationDataService struct {
	ctrl     *gomock.Controller
	recorder *MockGeolocationDataServiceMockRecorder
}

// MockGeolocationDataServiceMockRecorder is the mock recorder for MockGeolocationDataService.
type MockGeolocationDataServiceMockRecorder struct {
	mock *MockGeolocationDataService
}

// NewMockGeolocationDataService creates a new mock instance.
func NewMockGeolocationDataService(ctrl *gomock.Controller) *MockGeolocationDataService {
	mock := &MockGeolocationDataService{ctrl: ctrl}
	mock.recorder = &MockGeolocationDataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeolocationDataService) EXPECT() *MockGeolocationDataServiceMockRecorder {
	return m.recorder
}

// GetGeolocationByIP mocks base method.
func (m *MockGeolocationDataService) GetGeolocationByIP(ipAddress string) (*domain.Geolocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeolocationByIP", ipAddress)
	ret0, _ := ret[0].(*domain.Geolocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeolocationByIP indicates an expected call of GetGeolocationByIP.
func (mr *MockGeolocationDataServiceMockRecorder) GetGeolocationByIP(ipAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeolocationByIP", reflect.TypeOf((*MockGeolocationDataService)(nil).GetGeolocationByIP), ipAddress)
}
