// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/geolocation/domain/geolocation.go

// Package mock is a generated GoMock package.
package mock

import (
	"context"
	"reflect"

	"go.uber.org/mock/gomock"

	"github.com/aruna-cande/geolocation/pkg/geolocation/domain"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddGeolocation mocks base method.
func (m *MockRepository) AddGeolocation(ctx context.Context, geolocations []*domain.Geolocation) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGeolocation", ctx, geolocations)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddGeolocation indicates an expected call of AddGeolocation.
func (mr *MockRepositoryMockRecorder) AddGeolocation(ctx, geolocations interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGeolocation", reflect.TypeOf((*MockRepository)(nil).AddGeolocation), ctx, geolocations)
}

// GetGeolocationByIP mocks base method.
func (m *MockRepository) GetGeolocationByIP(ctx context.Context, ipAddress string) (*domain.Geolocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeolocationByIP", ctx, ipAddress)
	ret0, _ := ret[0].(*domain.Geolocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeolocationByIP indicates an expected call of GetGeolocationByIP.
func (mr *MockRepositoryMockRecorder) GetGeolocationByIP(ctx, ipAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeolocationByIP", reflect.TypeOf((*MockRepository)(nil).GetGeolocationByIP), ctx, ipAddress)
}
