apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: importer
  namespace: geolocation
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: importer-task
              image: gcr.io/PROJECT_ID/IMAGE:TAG
              securityContext:
                privileged: true
                capabilities:
                  add:
                    - SYS_ADMIN
              lifecycle:
                postStart:
                  exec:
                    command: [ "gcsfuse", "--implicit-dirs", "geolocation-importer-data", "/tmp/data" ]
                preStop:
                  exec:
                    command: [ "fusermount", "-u", "/tmp/data" ]
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "100m"
                limits:
                  memory: "128Mi"
                  cpu: "500m"
              ports:
                - containerPort: 8080
              env:
                - name: POSTGRES_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: geolocation-config
                      key: postgres_host
                - name: POSTGRES_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: geolocation-config
                      key: postgres_port
                - name: POSTGRES_DB
                  valueFrom:
                    configMapKeyRef:
                      name: geolocation-config
                      key: postgres_db
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: geolocation-secrets
                      key: postgres_user
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: geolocation-secrets
                      key: postgres_password
              command: ["./app/importer", "/tmp/data/data_dump.csv" ]
          restartPolicy: OnFailure
#          volumes:
#            - name: datadump
#              persistentVolumeClaim:
#                claimName: importer-claim