apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: importer-claim
  namespace: geolocation
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard