FROM golang:1.16
EXPOSE 8080

RUN echo "deb http://packages.cloud.google.com/apt gcsfuse-jessie main" | tee /etc/apt/sources.list.d/gcsfuse.list \
    && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - \
    && apt-get update \
    && apt-get -y install gcsfuse

RUN mkdir geolocation
COPY . /geolocation
WORKDIR /geolocation/cmd/geolocation-api
RUN go build -o /app .
ENTRYPOINT ["/app"]